# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Niko Yuwono
description:      'My blog about Computer Vision and Android Development.</br>Follow me <a href="https://twitter.com/niko_yuwono" target="_blank">@niko_yuwono</a>.'
url:              http://nikoyuwono.github.io/
baseurl:          /

author:
  name:           'Niko Yuwono'
  url:            https://twitter.com/niko_yuwono

paginate:         1

# Custom vars
version:          0.1

excerpt_separator: "<!-- more -->" # Adds read more feature

github:
  repo:           https://github.com/NikoYuwono
  
# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
    - jekyll-redirect-from
