# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Niko Yuwono
description:      'Hello, I''m Niko Yuwono. I''m a software engineer based in Tokyo, Japan and this is my blog about Computer Vision and Android Development.'
url:              http://nikoyuwono.com
baseurl:          /

author:
  name:           'Niko Yuwono'
  url:            https://twitter.com/niko_yuwono

paginate:         5

# Custom vars
version:          0.1

excerpt_separator: "<!-- more -->" # Adds read more feature

github:           https://github.com/NikoYuwono
stackoverflow:    http://stackoverflow.com/users/1545363/niko-yuwono
linkedin:         https://www.linkedin.com/in/nikoyuwono
twitter:          https://twitter.com/niko_yuwono
  
disqusid:         nikoyuwono

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
    - jekyll-redirect-from
